name: "Zensical Action"
description: "Easily Build, Upload and Deploy Zensical Docs to GitHub Pages or any other Service."
author: "Shane"

branding:
  icon: "book-open"
  color: "orange"

inputs:
  version:
    description: "Zensical Version"
  python-version:
    description: "Python Version"
  uv-version:
    description: "UV Version"
  directory:
    description: "Build Directory"
    default: "."
  path:
    description: "Site Path"
    default: "site"
  checkout:
    description: "Checkout Project"
    default: "true"
  upload:
    description: "Upload: github-pages, artifact, false"
    default: "github-pages"
  name:
    description: "Artifact Name"
    default: "artifact"
  deploy:
    description: "Deploy to GitHub Pages"
    default: "true"
  prepare:
    description: "Prepare Script (Before Build)"
  post:
    description: "Post Script (After Build)"
  summary:
    description: "Add Job Summary"
    default: "true"

outputs:
  page_url:
    description: "Zensical Version"
    value: ${{ steps.deployment.outputs.page_url }}
  version:
    description: "Zensical Version"
    value: ${{ steps.install.outputs.version }}
  path:
    description: "Site Directory"
    value: ${{ inputs.path }}
  name:
    description: "Artifact Name"
    value: ${{ inputs.upload == 'github-pages' && 'github-pages' || inputs.name }}

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v5

    - name: "Install UV"
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
        python-version: ${{ inputs.python-version }}

    - name: "Install Zensical"
      id: install
      shell: bash
      run: |
        if [ -n "${{ inputs.version }}" ]; then
           uv tool install "zensical==${{ inputs.version }}"
        else
           uv tool install zensical
        fi
        version="$(zensical --version)"
        echo "version=${version}" >> "$GITHUB_OUTPUT"
        echo "ZENSICAL_VERSION=${version}" >> "$GITHUB_ENV"

    - name: "Prepare"
      if: ${{ inputs.prepare }}
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        ${{ inputs.prepare }}

    - name: "Build"
      id: build
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        zensical build -c

    - name: "Post"
      if: ${{ inputs.post }}
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: |
        ${{ inputs.post }}

    - name: "Upload Artifact"
      if: ${{ inputs.upload == 'artifact' }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: "error"
        include-hidden-files: true

    - name: "Upload Pages Artifact"
      if: ${{ inputs.upload == 'github-pages' }}
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ inputs.path }}

    - name: "Deploy Pages"
      if: ${{ inputs.deploy == 'true' && inputs.upload == 'github-pages' }}
      id: deployment
      uses: actions/deploy-pages@v4

    - name: "Summary"
      if: ${{ always() && inputs.summary == 'true' }}
      env:
        path: ${{ inputs.path }}
        version: ${{ steps.install.outputs.version || 'unknown' }}
      continue-on-error: true
      shell: bash
      run: |
        markdown="# Zensical Action\n\n"
        markdown+="zensical version: \`${version}\`\n\n"
        if [ "${{ steps.build.outcome }}" == "success" ];then
          markdown+="✅ Build Success\n\n"
        else
          markdown+="⛔ Build Failure\n\n"
        fi
        if [ -d "${path}" ];then
          markdown+="<details><summary>Build Tree</summary>\n\n\`\`\`text\n"
          markdown+="$(tree ${path} || ls -lAhR ${path} 2>&1 ||:)\n"
          markdown+="\`\`\`\n\n</details>\n\n"
        else
          markdown+="⛔ Path Not Found: ${path}\n\n"
        fi
        markdown+="---\n\n"
        echo -e "${markdown}" >> $GITHUB_STEP_SUMMARY
